name: dbt_streaming_project
version: '1.0'
profile: dbt_streaming_project
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  dbt_streaming_project:
    source:
      +materialized: table_with_connector
